# Generated by Django 3.1.3 on 2021-02-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_auto_20210204_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionpaper',
            old_name='qtnFile',
            new_name='questionPaperName',
        ),
    ]
