# Generated by Django 3.1.3 on 2021-02-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_auto_20210205_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='questionPaperName',
            field=models.FileField(upload_to=''),
        ),
    ]
